/* eslint-disable @typescript-eslint/no-explicit-any */
import { NextRequest, NextResponse } from "next/server";
import { createClient } from "@supabase/supabase-js";

function database(){const url=process.env.NEXT_PUBLIC_SUPABASE_URL||process.env.SUPABASE_URL,key=process.env.SUPABASE_SECRET_KEY||process.env.SUPABASE_SERVICE_ROLE_KEY;if(!url||!key)return null;return createClient(url,key,{auth:{persistSession:false,autoRefreshToken:false}})}
export async function GET(){const db=database();if(!db)return NextResponse.json({error:"Database is not connected."},{status:503});const [{data:invoiceRows,error:invoiceError},{data:doRows,error:doError}]=await Promise.all([
 db.from("invoices").select("id,invoice_number,invoice_date,po_number,gst_rate,deposit,payment_method,remarks,status,created_at,customer:customers(company_name,billing_address,contact_person,contact_number),items:invoice_items(id,product_model,sku,product_type,description,brand,quantity,unit_price,remarks),delivery_order:delivery_orders(id,do_number)").is("deleted_at",null).order("created_at",{ascending:false}),
 db.from("delivery_orders").select("id,do_number,delivery_date,delivery_address,contact_person,contact_number,remarks,status,created_at,invoice:invoices(id,invoice_number),customer:customers(company_name,billing_address,contact_person,contact_number),items:delivery_order_items(id,product_model,sku,product_type,description,brand,quantity,unit_price,remarks)").is("deleted_at",null).order("created_at",{ascending:false})
 ]);if(invoiceError||doError)return NextResponse.json({error:invoiceError?.message||doError?.message},{status:400});
 const customer=(raw:any)=>({name:raw?.company_name||"",address:raw?.billing_address||"",attention:raw?.contact_person||"",phone:raw?.contact_number||""});const items=(rows:any[]=[])=>rows.map(x=>({id:x.id,model:x.product_model,sku:x.sku,type:x.product_type,description:x.description,brand:x.brand,quantity:Number(x.quantity),unitPrice:Number(x.unit_price),remarks:x.remarks||""}));
 const invoices=(invoiceRows||[]).map((x:any)=>({id:x.id,invoiceNumber:x.invoice_number,invoiceDate:x.invoice_date,customer:customer(x.customer),doNumber:x.delivery_order?.[0]?.do_number||"—",doId:x.delivery_order?.[0]?.id||"",poNumber:x.po_number||"",items:items(x.items),gstRate:Number(x.gst_rate),deposit:Number(x.deposit),paymentStatus:String(x.status).replaceAll("_"," ").replace(/\b\w/g,(c:string)=>c.toUpperCase()),paymentMethod:x.payment_method||"",collectionMethod:"Delivery by Tesvila",installationOption:"Supply only",remarks:x.remarks||"",createdBy:"Tesvila User",createdAt:x.created_at}));
 const deliveryOrders=(doRows||[]).map((x:any)=>({id:x.id,doNumber:x.do_number,deliveryDate:x.delivery_date,customer:customer(x.customer),invoiceNumber:x.invoice?.invoice_number||"—",invoiceId:x.invoice?.id,deliveryAddress:x.delivery_address,deliveryContact:x.contact_person||"",deliveryPhone:x.contact_number||"",items:items(x.items),status:String(x.status).replaceAll("_"," ").replace(/\b\w/g,(c:string)=>c.toUpperCase()),remarks:x.remarks||"",createdBy:"Tesvila User",createdAt:x.created_at}));return NextResponse.json({invoices,deliveryOrders})}
export async function POST(req:NextRequest){const db=database();if(!db)return NextResponse.json({error:"Database is not connected. Add the Supabase URL and service key before saving documents."},{status:503});const body=await req.json();if(!["invoice_with_do","delivery_order"].includes(body.type))return NextResponse.json({error:"Unknown document type"},{status:400});const fn=body.type==="invoice_with_do"?"create_invoice_with_do":"create_delivery_order_only";const {data,error}=await db.rpc(fn,{p_payload:body});if(error)return NextResponse.json({error:error.message},{status:400});return NextResponse.json(data,{status:201})}
export async function PATCH(req:NextRequest){const db=database();if(!db)return NextResponse.json({error:"Database is not connected."},{status:503});const body=await req.json();const fn=body.type==="invoice"?"update_invoice_document":body.type==="delivery_order"?"update_delivery_order_document":null;if(!fn)return NextResponse.json({error:"Unknown document type"},{status:400});const {error}=await db.rpc(fn,{p_id:body.record.id,p_payload:body.record});if(error)return NextResponse.json({error:error.message},{status:400});return NextResponse.json({ok:true})}
export async function DELETE(req:NextRequest){const db=database();if(!db)return NextResponse.json({error:"Database is not connected."},{status:503});const body=await req.json();const table=body.type==="invoice"?"invoices":body.type==="delivery_order"?"delivery_orders":null;if(!table)return NextResponse.json({error:"Unknown document type"},{status:400});const {error}=await db.from(table).update({deleted_at:new Date().toISOString()}).eq("id",body.id);if(error)return NextResponse.json({error:error.message},{status:400});await db.from("audit_logs").insert({action:"document_deleted",entity_type:body.type,entity_id:body.id,new_values:{soft_deleted:true}});return NextResponse.json({ok:true})}
